#######################################
#  MultiQC Configuration File for fastQC
#######################################

# Configuration settings are taken from the following locations, in order:
# - Hardcoded in MultiQC (multiqc/utils/config.py)
# - <installation_dir>/multiqc_config.yaml
# - ~/.multiqc_config.yaml
# - Command line options

# Title to use for the report.
title: null

# Default output filenames
output_fn_name: 'multiqc_report.html'
data_dir_name: 'multiqc_data'

# Prepend sample names with their directory. Useful if analysing the
# sample samples with different parameters.
prepend_dirs: false

# Whether to create the parsed data directory in addition to the report
make_data_dir: True

# Cleaning options for sample names. Typically, sample names are detected
# from an input filename. If any of these strings are found, they and any
# text to their right will be discarded.
# Two options here - fn_clean_exts will replace the defaults,
## extra_fn_clean_exts will append to the defaults
# extra_fn_clean_exts: #applicable to all
#    - type: 'replace' / 'remove'
#      pattern: 'NGS95a_'

# Ignore files larger than this when searcing for logs (bytes)
log_filesize_limit: 5000000

# MultiQC skips a couple of debug messages when searching files as the
# log can get very verbose otherwise. Re-enable here to help debugging.
report_readerrors: False
report_imgskips: False

# Opt-out of remotely checking that you're running the latest version
no_version_check: False

# How to plot graphs. Different templates can override these settings, but
# the default template can use interactive plots (Javascript using HighCharts)
# or flat plots (images, using MatPlotLib). With interactive plots, the report
# can prevent automatically rendering all graphs if there are lots of samples
# to prevent the browser being locked up when the report opens.
plots_force_flat: False          # Try to use only flat image graphs
plots_force_interactive: False   # Try to use only interactive javascript graphs
plots_flat_numseries: 100        # If neither of the above, use flat if > this number of datasets
num_datasets_plot_limit: 50      # If interactive, don't plot on load if > this number of datasets
max_table_rows: 500              # Swap tables for a beeswarm plot above this

# Overwrite module filename search patterns. See multiqc/utils/search_patterns.yaml
# for the defaults. Remove a default by setting it to null.
sp:
    fastqc/data:
        fn: '*.stats-fastqc.txt'
    verifybamid/selfsm:
        fn: '*.selfSM'
    samtools/flagstat:
        contents: 'in total (QC-passed reads + QC-failed reads)'
        shared: true

# Overwrite the defaults of which table columns are visible by default
#    FastQC:
#        percent_fails: False
#        total_sequences: True
