#!/bin/bash
# multiqc 1.0.0
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.

# Exit at any point if there is any error and output each line as it is executed (for debugging)
set -e -x -o pipefail

main() {

    # Download the config file and qc files into 'inputs' folder
    mkdir inputs
    dx download "$eggd_multiqc_config_file" -o eggd_multiqc_config_file
    dx download "$project_for_multiqc:fastqc/*" -o ./inputs/ # download fastqc reports
    dx download "$project_for_multiqc:verifybamid/*" -o ./inputs/ # download verifybamid reports
    
    # Download the tar-zipped docker image either from input or default
    if [ -f "$multiqc_docker_image" ]; then
        dx download "$multiqc_docker_image"
        image=$(dx describe "$multiqc_docker_image" --name)
    else
        dx download project-FpG6p8j4ZY3X4KGQB9KK5zZf:file-FpQg5fj4g59gqqfK3gGkFVQg
        image=$(dx describe project-FpG6p8j4ZY3X4KGQB9KK5zZf:file-FpQg5fj4g59gqqfK3gGkFVQg --name)
    fi

    # Create the output folders that will be recognised by the job upon completion
    outdir=out/multiqc_data_files && mkdir -p ${outdir}
    report_outdir=out/multiqc_html_report && mkdir -p ${report_outdir}
    project=$(echo $project_for_multiqc | sed 's/003_//')
  
    # Load the tar-zipped docker image
    docker load -i ${image} #multiqc_v1.8.tar
    # The docker -v flag mounts a local directory to the docker environment in the format:
    #    -v local_dir:docker_dir
    # MultiQC is run with the following parameters :
    #    multiqc <dir containing files> -n <path/to/output> -c </path/to/config>
    docker run -v ${PWD}:${PWD} -w ${PWD} ewels/multiqc:1.8 ./inputs/ -n ./${outdir}/${project}-multiqc.html -c /home/dnanexus/eggd_multiqc_config_file

    # Move the config file to the multiqc data output folder. This was created by running multiqc
    mv eggd_multiqc_config_file ${outdir}/${project}-multiqc_data/
    # Move the multiqc report HTML to the output directory for uploading
    mv ${outdir}/${project}-multiqc.html ${report_outdir}

    # Upload results
    dx-upload-all-outputs
   
    #html_report=$(dx upload html_report --brief)
    # The following line(s) use the utility dx-jobutil-add-output to format and
    # add output variables to your job's output as appropriate for the output
    # class.  Run "dx-jobutil-add-output -h" for more information on what it does.
}
